name = "\n Anandhi Jayabalan\'s practise \t"
"""print(name.strip())
print(len(name))
print(name[:])
print(name[::-1])
print(name[8])
print(name[8:18])
print(name[:18])
print(name[:-1])
print(name[-1])
print(name[7:17:2])
print("hi " + " welcome to " + name)
print( "*" * 12)"""
print('but life is good!'.split()) 
print('help you!'.replace('you', 'me')) 
print('help you!'.upper()) 
print('help you!'.startswith('h')) 
print('help you!'.endswith('u')) 
print('WELCOME'.lower()) 
print('Hi ! there !'.find('i'))
print('Hi ! there !'.count('e'))